name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: wine_marketplace_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter shared build
          pnpm --filter database build

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/wine_marketplace_test
        run: |
          pnpm --filter database db:migrate

      - name: Install Playwright browsers
        run: pnpm --filter e2e-tests playwright install --with-deps

      - name: Start applications
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/wine_marketplace_test
        run: |
          pnpm --filter api build
          pnpm dev &
          sleep 30

      - name: Run E2E tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/wine_marketplace_test
        run: pnpm --filter e2e-tests test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/e2e-tests/playwright-report/
          retention-days: 30

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results
          path: packages/e2e-tests/test-results/
          retention-days: 30